income = int(input("What's your monthly income ? "))
print(f"Your monthly income is ${income}")
expense = float(input("What's your monthly expense ? "))
balance = round(income - expense, 2)
print(f"Your balance is ${balance}")